// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBXO1E3BpHlgNbJfohloy9p-XxMjip4p0',
    appId: '1:325219924400:web:72ae246497d75a6ab53e75',
    messagingSenderId: '325219924400',
    projectId: 'symptomchecker-bachelorthesis',
    authDomain: 'symptomchecker-bachelorthesis.firebaseapp.com',
    storageBucket: 'symptomchecker-bachelorthesis.appspot.com',
    measurementId: 'G-KBPPNVBPCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2xb6L09NdfwoMAyYwEZ9GvqmucOTG6qc',
    appId: '1:325219924400:android:2326b24fdafeab5eb53e75',
    messagingSenderId: '325219924400',
    projectId: 'symptomchecker-bachelorthesis',
    storageBucket: 'symptomchecker-bachelorthesis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4OQNwth2nd1Qwkw1PtBsvtng5sf_yaOM',
    appId: '1:325219924400:ios:54608effb0ec4ef6b53e75',
    messagingSenderId: '325219924400',
    projectId: 'symptomchecker-bachelorthesis',
    storageBucket: 'symptomchecker-bachelorthesis.appspot.com',
    iosClientId: '325219924400-33ur23c5om9p7v6djngl5rf6jmc5phkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.diseaseApplicationBachelorThesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4OQNwth2nd1Qwkw1PtBsvtng5sf_yaOM',
    appId: '1:325219924400:ios:54608effb0ec4ef6b53e75',
    messagingSenderId: '325219924400',
    projectId: 'symptomchecker-bachelorthesis',
    storageBucket: 'symptomchecker-bachelorthesis.appspot.com',
    iosClientId: '325219924400-33ur23c5om9p7v6djngl5rf6jmc5phkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.diseaseApplicationBachelorThesis',
  );
}
